function onGameOverStart()
setProperty('health.visible', false)
setProperty('health2.visible', false)
setProperty('icons1.visible', false)
setProperty('icons2.visible', false)
setProperty('icons1.visible', false)
setProperty('icons2.visible', false)
setProperty('icons12.visible', false)
setProperty('icons33.visible', false)
setProperty('icons5.visible', false)
setProperty('icons4.visible', false)
setProperty('health_filler.visible', false)
setProperty('icons7.visible', false)
end